In [212]:
import pandas as pd
import numpy as np
import cv2

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential


In [213]:
to_train = pd.read_csv("/Users/elsa/Desktop/Bootcamp The Bridge/The_Bridge/Ds_Bootcamp_Elsa/Ejercicios/competicion_kaggle/Competicion_how_am_I_feeling/how-am-i-feeling/train_set.csv")
to_test = pd.read_csv("/Users/elsa/Desktop/Bootcamp The Bridge/The_Bridge/Ds_Bootcamp_Elsa/Ejercicios/competicion_kaggle/Competicion_how_am_I_feeling/how-am-i-feeling/test_set.csv")

In [214]:
to_train

label  id_img               path
0       happy   22373    happy/22373.jpg
1       happy   21433    happy/21433.jpg
2       happy   12418    happy/12418.jpg
3       happy   21278    happy/21278.jpg
4       happy    8081    happy/08081.jpg
...       ...     ...                ...
6171  sadness   11346  sadness/11346.jpg
6172  sadness    4441  sadness/04441.jpg
6173  sadness   15236  sadness/15236.jpg
6174  sadness   27361  sadness/27361.jpg
6175  sadness   25239  sadness/25239.jpg

[6176 rows x 3 columns]

In [215]:
# Convertimos todas las imagenes en un array:
X_train = []
for elem in to_train.path:
    path = "totrain/totrain/" + elem
    X_train.append(cv2.imread(path))
#to_train2
X_train = np.array(X_train)
print(X_train)
print("####################")
print(X_train.shape)

[[[[ 25  25  25]
   [ 44  44  44]
   [ 56  56  56]
   ...
   [ 34  34  34]
   [ 11  11  11]
   [ 17  17  17]]

  [[ 30  30  30]
   [ 46  46  46]
   [ 54  54  54]
   ...
   [ 45  45  45]
   [ 19  19  19]
   [ 17  17  17]]

  [[ 38  38  38]
   [ 50  50  50]
   [ 55  55  55]
   ...
   [ 53  53  53]
   [ 25  25  25]
   [ 12  12  12]]

  ...

  [[110 110 110]
   [116 116 116]
   [129 129 129]
   ...
   [ 40  40  40]
   [ 63  63  63]
   [ 34  34  34]]

  [[110 110 110]
   [138 138 138]
   [135 135 135]
   ...
   [ 51  51  51]
   [ 52  52  52]
   [ 30  30  30]]

  [[ 93  93  93]
   [142 142 142]
   [127 127 127]
   ...
   [ 73  73  73]
   [ 48  48  48]
   [ 33  33  33]]]


 [[[ 33  33  33]
   [ 29  29  29]
   [ 22  22  22]
   ...
   [ 22  22  22]
   [ 19  19  19]
   [ 26  26  26]]

  [[ 36  36  36]
   [ 29  29  29]
   [ 20  20  20]
   ...
   [ 29  29  29]
   [ 23  23  23]
   [ 24  24  24]]

  [[ 33  33  33]
   [ 25  25  25]
   [ 15  15  15]
   ...
   [ 30  30  30]
   [ 25  25  25]
   [ 21  21

In [216]:
# con esto paso de 3 canales a uno
# aplico la funcion cv2.cvtColor a cada elemento de X_train y luego lo paso a array
new_array = [cv2.cvtColor(pic, cv2.COLOR_BGR2GRAY) for pic in X_train]
X_train = np.array(new_array)

In [217]:
# Convertimos todas las imagenes en un array:
to_test2 = []
for elem in to_test.path:
    path = "totrain/totrain/" + elem
    to_test2.append(cv2.imread(path))

to_test2 = np.array(to_test)
print(to_test2)
print("####################")
print(to_test2.shape)

[[18341 'to_pred/18341.jpg']
 [13176 'to_pred/13176.jpg']
 [23945 'to_pred/23945.jpg']
 ...
 [16629 'to_pred/16629.jpg']
 [24322 'to_pred/24322.jpg']
 [23412 'to_pred/23412.jpg']]
####################
(4117, 2)


In [218]:
# Necesito obtener los labels para poder conseguir y_train
lista_label = []
for elem in to_train.label:
    #lista_label.append(cv2.imread(elem))
    lista_label.append(elem)

# tomo una posición para que no me imprima toda la lista
lista_label[6]

'happy'

In [219]:
# 2._ OTRA FORMA DE APLICAR LABELENCODER
y_train = np.asarray(lista_label)
y_train

array(['happy', 'happy', 'happy', ..., 'sadness', 'sadness', 'sadness'],
      dtype='<U7')

In [220]:
# APLICAR LABELENCODER a y_train
le = LabelEncoder()
y_train = le.fit_transform(y_train)
# train_labels = y_train
y_train

array([0, 0, 0, ..., 1, 1, 1])

In [221]:
print("X_train:  ", X_train.shape)
print("y_train:  ",y_train.shape)
print("to_test:  ",to_test2.shape)

X_train:   (6176, 48, 48)
y_train:   (6176,)
to_test:   (4117, 2)


In [222]:
# 4-Creamos sets de Entrenamiento y Test, Validación y Preprocesar

train_X,test_X,train_Y,test_Y = train_test_split(X_train,y_train,test_size=0.2)
print('Training data shape : ', train_X.shape, train_Y.shape)
print('Testing data shape : ', test_X.shape, test_Y.shape)

Training data shape :  (4940, 48, 48) (4940,)
Testing data shape :  (1236, 48, 48) (1236,)


In [223]:
train_X = train_X.astype('float32')
test_X = test_X.astype('float32')
train_X = train_X / 255.
test_X = test_X / 255.
 
print(train_X.shape)


(4940, 48, 48)


In [152]:
# 4-Creamos sets de Entrenamiento y Test, Validación y Preprocesar

train_X,test_X,train_Y,test_Y = train_test_split(X_train,y_train,test_size=0.2)
print('Training data shape : ', train_X.shape, train_Y.shape)
print('Testing data shape : ', test_X.shape, test_Y.shape)
 
train_X = train_X.astype('float32')
test_X = test_X.astype('float32')
train_X = train_X / 255.
test_X = test_X / 255.
 
print(train_X.shape)

# Change the labels from categorical to one-hot encoding
train_Y_one_hot = to_categorical(train_Y)
test_Y_one_hot = to_categorical(test_Y)
 
# Display the change for category label using one-hot encoding
print('Original label:', train_Y[0])
print('After conversion to one-hot:', train_Y_one_hot[0])
 
train_X,valid_X,train_label,valid_label = train_test_split(train_X, train_Y_one_hot, test_size=0.2, random_state=13)
 
print(train_X.shape,valid_X.shape,train_label.shape,valid_label.shape)

Training data shape :  (4940, 48, 48) (4940,)
Testing data shape :  (1236, 48, 48) (1236,)
(4940, 48, 48)
Original label: 1
After conversion to one-hot: [0. 1.]
(3952, 48, 48) (988, 48, 48) (3952, 2) (988, 2)


In [224]:
# 5 – Creamos la red
classes = np.unique(y_train)
nClasses = len(classes)

INIT_LR = 1e-3
epochs = 6
batch_size = 48
 

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='linear',padding='same',input_shape=(4940, 48, 48))

model.add(MaxPooling2D((2, 2),padding='same'))
model.add(Dropout(0.5))
 
model.add(Flatten())
model.add(Dense(32, activation='linear'))

model.add(Dropout(0.5)) 
model.add(Dense(nClasses, activation='softmax'))
 
model.summary()
 
model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adagrad(lr=INIT_LR, decay=INIT_LR / 100),metrics=['accuracy'])

SyntaxError: invalid syntax (<ipython-input-224-5d667676601e>, line 13)

In [ ]:
# 6-Entrenamos la CNN
sport_train_dropout = model.fit(train_X, train_Y, 
batch_size=batch_size,
epochs=epochs,
verbose=1,
validation_data=(valid_X, valid_label))

In [ ]:
# guardamos la red, para reutilizarla en el futuro, sin tener que volver a entrenar
sport_model.save("how_am_I_feeling.h5py")

In [225]:
# RED DE CLASIFICACIÓN
# Modelo

model = Sequential()
model.add(Dense(64, input_shape=(4940, 48, 48), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(256, activation='sigmoid'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))
model.summary()

Model: "sequential_31"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_64 (Dense)             (None, 4940, 48, 64)      3136      
_________________________________________________________________
dropout_44 (Dropout)         (None, 4940, 48, 64)      0         
_________________________________________________________________
dense_65 (Dense)             (None, 4940, 48, 256)     16640     
_________________________________________________________________
dropout_45 (Dropout)         (None, 4940, 48, 256)     0         
_________________________________________________________________
dense_66 (Dense)             (None, 4940, 48, 2)       514       
Total params: 20,290
Trainable params: 20,290
Non-trainable params: 0
_________________________________________________________________


In [226]:
model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adagrad(lr=INIT_LR, decay=INIT_LR / 100),metrics=['accuracy'])

In [184]:
y_train = to_categorical(y_train)
#y_test = to_categorical(y_test, 3)

In [227]:
hist_model = model.fit(X_train, y_train,
  batch_size=32,
  epochs=5,
  verbose=1,
  validation_split=0.1,
  shuffle=True)

Epoch 1/5


ValueError: in user code:

    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:748 train_step
        loss = self.compiled_loss(
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/compile_utils.py:204 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/losses.py:149 __call__
        losses = ag_call(y_true, y_pred)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/losses.py:253 call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/losses.py:1535 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/backend.py:4687 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/framework/tensor_shape.py:1134 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 1) and (None, 48, 2) are incompatible
