In [325]:
import pandas as pd
import numpy as np
import cv2

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential

In [326]:
to_train = pd.read_csv("/Users/elsa/Desktop/Bootcamp The Bridge/The_Bridge/Ds_Bootcamp_Elsa/Ejercicios/competicion_kaggle/Competicion_how_am_I_feeling/how-am-i-feeling/train_set.csv")
to_test = pd.read_csv("/Users/elsa/Desktop/Bootcamp The Bridge/The_Bridge/Ds_Bootcamp_Elsa/Ejercicios/competicion_kaggle/Competicion_how_am_I_feeling/how-am-i-feeling/test_set.csv")

In [327]:
to_train

label  id_img               path
0       happy   22373    happy/22373.jpg
1       happy   21433    happy/21433.jpg
2       happy   12418    happy/12418.jpg
3       happy   21278    happy/21278.jpg
4       happy    8081    happy/08081.jpg
...       ...     ...                ...
6171  sadness   11346  sadness/11346.jpg
6172  sadness    4441  sadness/04441.jpg
6173  sadness   15236  sadness/15236.jpg
6174  sadness   27361  sadness/27361.jpg
6175  sadness   25239  sadness/25239.jpg

[6176 rows x 3 columns]

In [328]:
# Convertimos todas las imagenes en un array:
X_train = []
for elem in to_train.path:
    path = "totrain/totrain/" + elem
    X_train.append(cv2.imread(path))
#to_train2
X_train = np.array(X_train)
print(X_train)
print("####################")
print(X_train.shape)

[[[[ 25  25  25]
   [ 44  44  44]
   [ 56  56  56]
   ...
   [ 34  34  34]
   [ 11  11  11]
   [ 17  17  17]]

  [[ 30  30  30]
   [ 46  46  46]
   [ 54  54  54]
   ...
   [ 45  45  45]
   [ 19  19  19]
   [ 17  17  17]]

  [[ 38  38  38]
   [ 50  50  50]
   [ 55  55  55]
   ...
   [ 53  53  53]
   [ 25  25  25]
   [ 12  12  12]]

  ...

  [[110 110 110]
   [116 116 116]
   [129 129 129]
   ...
   [ 40  40  40]
   [ 63  63  63]
   [ 34  34  34]]

  [[110 110 110]
   [138 138 138]
   [135 135 135]
   ...
   [ 51  51  51]
   [ 52  52  52]
   [ 30  30  30]]

  [[ 93  93  93]
   [142 142 142]
   [127 127 127]
   ...
   [ 73  73  73]
   [ 48  48  48]
   [ 33  33  33]]]


 [[[ 33  33  33]
   [ 29  29  29]
   [ 22  22  22]
   ...
   [ 22  22  22]
   [ 19  19  19]
   [ 26  26  26]]

  [[ 36  36  36]
   [ 29  29  29]
   [ 20  20  20]
   ...
   [ 29  29  29]
   [ 23  23  23]
   [ 24  24  24]]

  [[ 33  33  33]
   [ 25  25  25]
   [ 15  15  15]
   ...
   [ 30  30  30]
   [ 25  25  25]
   [ 21  21

In [270]:
# Convertimos todas las imagenes en un array:
to_test2 = []
for elem in to_test.path:
    path = "totrain/totrain/" + elem
    to_test2.append(cv2.imread(path))

to_test2 = np.array(to_train2)
print(to_test2)
print("####################")
print(to_test2.shape)

[[[[ 25  25  25]
   [ 44  44  44]
   [ 56  56  56]
   ...
   [ 34  34  34]
   [ 11  11  11]
   [ 17  17  17]]

  [[ 30  30  30]
   [ 46  46  46]
   [ 54  54  54]
   ...
   [ 45  45  45]
   [ 19  19  19]
   [ 17  17  17]]

  [[ 38  38  38]
   [ 50  50  50]
   [ 55  55  55]
   ...
   [ 53  53  53]
   [ 25  25  25]
   [ 12  12  12]]

  ...

  [[110 110 110]
   [116 116 116]
   [129 129 129]
   ...
   [ 40  40  40]
   [ 63  63  63]
   [ 34  34  34]]

  [[110 110 110]
   [138 138 138]
   [135 135 135]
   ...
   [ 51  51  51]
   [ 52  52  52]
   [ 30  30  30]]

  [[ 93  93  93]
   [142 142 142]
   [127 127 127]
   ...
   [ 73  73  73]
   [ 48  48  48]
   [ 33  33  33]]]


 [[[ 33  33  33]
   [ 29  29  29]
   [ 22  22  22]
   ...
   [ 22  22  22]
   [ 19  19  19]
   [ 26  26  26]]

  [[ 36  36  36]
   [ 29  29  29]
   [ 20  20  20]
   ...
   [ 29  29  29]
   [ 23  23  23]
   [ 24  24  24]]

  [[ 33  33  33]
   [ 25  25  25]
   [ 15  15  15]
   ...
   [ 30  30  30]
   [ 25  25  25]
   [ 21  21

In [329]:
# Necesito obtener los labels para poder conseguir y_train
lista_label = []
for elem in to_train.label:
    #lista_label.append(cv2.imread(elem))
    lista_label.append(elem)

# tomo una posición para que no me imprima toda la lista
lista_label[6]

'happy'

In [330]:
# 2._ OTRA FORMA DE APLICAR LABELENCODER
y_train = np.asarray(lista_label)
y_train

array(['happy', 'happy', 'happy', ..., 'sadness', 'sadness', 'sadness'],
      dtype='<U7')

In [331]:
# APLICAR LABELENCODER a y_train
le = LabelEncoder()
y_train = le.fit_transform(lista_label)
# train_labels = y_train
y_train

array([0, 0, 0, ..., 1, 1, 1])

In [332]:
print("X_train:  ", X_train.shape)
print("y_train:  ",y_train.shape)
print("to_test:  ",to_test2.shape)

X_train:   (6176, 48, 48, 3)
y_train:   (6176,)
to_test:   (6176, 48, 48, 3)


In [333]:
# con esto paso de 3 canales a uno
# aplico la funcion cv2.cvtColor a cada elemento de X_train y luego lo paso a array
new_array = [cv2.cvtColor(pic, cv2.COLOR_BGR2GRAY) for pic in X_train]
X_train = np.array(new_array)

In [335]:

y_train = np.array(y_train)



In [336]:
new_array_t = [cv2.cvtColor(pic, cv2.COLOR_BGR2GRAY) for pic in to_test2]
X_test = np.array(new_array_t)

In [337]:
# Este método vale si no utilizo capa convolucional
print("X_train", X_train.shape)
print("y_train", y_train.shape)
print("X_test", X_test.shape)

X_train (6176, 48, 48)
y_train (6176,)
X_test (6176, 48, 48)


In [ ]:
######

In [291]:
train_label = np.array(train_labels)

#new_array_t = [cv2.cvtColor(pic, cv2.COLOR_BGR2GRAY) for pic in train_label]
train_label = np.array(new_array_t) #--> = y_train
train_label.shape

(6176, 48, 48)

In [149]:
# con esto normalizo los pixeles
X_train = X_train / 255.0
X_test = X_test / 255.0

In [339]:
# Dividir el conjunto
# Creamos el set de entrenamiento y test

(train_images, train_labels), (test_images, test_labels) = train_test_split(X_train, y_train = 0.30)

TypeError: Invalid parameters passed: {'y_train': 0.3}

In [295]:
# con esto saco los elementos (números) de dentro del array pequeño que solo tiene un número
# esto se llama flatten un array
y_train = np.array([num for arr in y_train for num in arr])
y_test = np.array([num for arr in y_test for num in arr])

TypeError: 'numpy.int64' object is not iterable

In [100]:
# Este método vale si no utilizo capa convolucional
X_train.shape

(6176, 48, 48)

In [ ]:
4-Creamos sets de Entrenamiento y Test, Validación y Preprocesar

In [340]:
train_X,test_X,train_Y,test_Y = train_test_split(X_train,y_train,test_size=0.2)
print('Training data shape : ', train_X.shape, train_Y.shape)
print('Testing data shape : ', test_X.shape, test_Y.shape)
 
train_X = train_X.astype('float32')
test_X = test_X.astype('float32')
train_X = train_X / 255.
test_X = test_X / 255.
 


# Change the labels from categorical to one-hot encoding
train_Y_one_hot = to_categorical(train_Y)
test_Y_one_hot = to_categorical(test_Y)
 
# Display the change for category label using one-hot encoding
print('Original label:', train_Y[0])
print('After conversion to one-hot:', train_Y_one_hot[0])
 
train_X,valid_X,train_label,valid_label = train_test_split(train_X, train_Y_one_hot, test_size=0.2, random_state=13)
 
print(train_X.shape,valid_X.shape,train_label.shape,valid_label.shape)

Training data shape :  (4940, 48, 48) (4940,)
Testing data shape :  (1236, 48, 48) (1236,)
Original label: 0
After conversion to one-hot: [1. 0.]
(3952, 48, 48) (988, 48, 48) (3952, 2) (988, 2)


In [ ]:

5 – Creamos la red

In [341]:
classes = np.unique(y_train)
nClasses = len(classes)
nClasses

2

In [342]:
INIT_LR = 1e-3
epochs = 6
batch_size = 48
 


sport_model = Sequential()
sport_model.add(Conv2D(32, kernel_size=(3, 3),activation='linear',padding='same',input_shape=(4940, 48, 48)))

sport_model.add(MaxPooling2D((2, 2),padding='same'))
sport_model.add(Dropout(0.5))
 
sport_model.add(Flatten())
sport_model.add(Dense(32, activation='linear'))

sport_model.add(Dropout(0.5)) 
sport_model.add(Dense(nClasses, activation='softmax'))
 
sport_model.summary()
 
sport_model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adagrad(lr=INIT_LR, decay=INIT_LR / 100),metrics=['accuracy'])


Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_11 (Conv2D)           (None, 4940, 48, 32)      13856     
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 2470, 24, 32)      0         
_________________________________________________________________
dropout_18 (Dropout)         (None, 2470, 24, 32)      0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 1896960)           0         
_________________________________________________________________
dense_20 (Dense)             (None, 32)                60702752  
_________________________________________________________________
dropout_19 (Dropout)         (None, 32)                0         
_________________________________________________________________
dense_21 (Dense)             (None, 2)               

In [ ]:
6-Entrenamos la CNN

In [343]:
sport_train_dropout = sport_model.fit(train_X, train_label, 
batch_size=batch_size,
epochs=epochs,
verbose=1,
validation_data=(valid_X, valid_label))



Epoch 1/6


ValueError: in user code:

    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:747 train_step
        y_pred = self(x, training=True)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/input_spec.py:191 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_18 is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: [None, 48, 48]


In [ ]:
# guardamos la red, para reutilizarla en el futuro, sin tener que volver a entrenar
sport_model.save("how_am_I_feeling.h5py")

In [346]:
# RED DE CLASIFICACIÓN
# Modelo

# Keras Sequential()es un tipo simple de red neuronal que consiste en una "pila" de capas ejecutadas en orden.
model_clasificador = keras.models.Sequential()
model_clasificador.add(keras.layers.Dense(512, input_shape=(48 ,48), activation='relu'))
model_clasificador.add(keras.layers.Dropout(0.5))
model_clasificador.add(keras.layers.Dense(256, activation='sigmoid'))
model_clasificador.add(keras.layers.Dropout(0.5))
model_clasificador.add(keras.layers.Dense(2, activation='softmax')) # --> se aplica porque hay dos clases. La suma total tiene que ser 100%
# el input son los arrays que pertenecen a cada frase

model_clasificador.compile(loss='categorical_crossentropy',
optimizer='adam',
metrics=['accuracy'])

# Cómo entrenar su red
hist_model_clasificador = model_clasificador.fit(train_X, train_label,
batch_size=32,
epochs=3,
verbose=1,
validation_split=0.1,
shuffle=True)

Epoch 1/3


ValueError: in user code:

    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/training.py:748 train_step
        loss = self.compiled_loss(
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/compile_utils.py:204 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/losses.py:149 __call__
        losses = ag_call(y_true, y_pred)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/losses.py:253 call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/losses.py:1535 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/backend.py:4687 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /Users/elsa/Library/Python/3.8/lib/python/site-packages/tensorflow/python/framework/tensor_shape.py:1134 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 2) and (None, 48, 2) are incompatible


In [ ]:
####################

In [70]:
# INTENTANDO OTRA FORMA OBTENER PATH:
import cv2
import os

img=[]
folder= "/Users/elsa/Desktop/Bootcamp The Bridge/The_Bridge/Ds_Bootcamp_Elsa/Ejercicios/competicion_kaggle/Competicion_how_am_I_feeling/how-am-i-feeling/totrain/totrain"
def load_images_from_folder(folder):
       images = []
       for filename in os.listdir(folder):
           img = cv2.imread(os.path.join(folder,filename))
           print(filename)
           if img is not None:
                images.append(img)
                print(images)
       return images
load_images_from_folder(folder)

happy
sadness


[]

In [69]:
img

[]

In [71]:
folder

'/Users/elsa/Desktop/Bootcamp The Bridge/The_Bridge/Ds_Bootcamp_Elsa/Ejercicios/competicion_kaggle/Competicion_how_am_I_feeling/how-am-i-feeling/totrain/totrain'

In [ ]:
##################

In [184]:
# OTRA FORMA DE OBTENER LAS IMAGENES DEL PATH
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

DATADIR = "/Users/elsa/Desktop/Bootcamp The Bridge/The_Bridge/Ds_Bootcamp_Elsa/Ejercicios/competicion_kaggle/Competicion_how_am_I_feeling/how-am-i-feeling/totrain/totrain"

CATEGORIES = ["happy", "sadness"]
lista=[]
for category in CATEGORIES:  # do dogs and cats
    path = os.path.join(DATADIR,category)  # create path to dogs and cats
    for img in os.listdir(path):  # iterate over each image per dogs and cats
        img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convert to array
        lista.append(img_array)
        #plt.imshow(img_array, cmap='gray')  # graph it
        #plt.show()  # display!

 


In [185]:
lista[4]

array([[207, 189, 190, ..., 119,  64,  98],
       [199, 174, 189, ..., 124,  62,  78],
       [192, 159, 185, ..., 131,  62,  50],
       ...,
       [188, 184, 146, ..., 198, 230, 252],
       [183, 154, 136, ..., 252, 248, 217],
       [ 91,  52, 112, ..., 139, 107, 108]], dtype=uint8)

In [187]:
print(img_array)

[[227 184 203 ... 226 230 239]
 [206 188 192 ... 230 237 237]
 [179 198 158 ... 230 244 237]
 ...
 [209 193 194 ... 210 217 210]
 [216 208 217 ... 179 182 187]
 [226 225 238 ... 172 173 188]]


In [186]:
lista[4].shape

(48, 48)

In [188]:
print(img_array.shape)

(48, 48)


In [201]:
IMG_SIZE = 40
new_array_list = []
for elem in lista:
    new_array = cv2.resize(elem, (IMG_SIZE, IMG_SIZE))
    new_array_list.append(new_array)
    #plt.imshow(new_array, cmap='gray')   #--->lo anulo porque me imprime todas las imagenes
    #plt.show()
new_array_list[70].shape

(40, 40)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
#Modelo de red convolucional

#Estructura base
cnn = Sequential()

#Primera capa convolucional
cnn.add(Conv2D(filters=32, kernel_size = (3,3), input_shape = (64,64,3), activation = "relu"))

#Maxpooling
cnn.add(MaxPooling2D(pool_size=(4,4)))

#Se pueden seguir agregando capas
#Segunda capa convolucional
#cnn.add(Conv2D(filters=32, kernel_size = (3,3), input_shape = (64,64,3), activation = "relu"))

#Maxpooling
#cnn.add(MaxPooling2D(pool_size=(4,4)))

#Capa de flattering
cnn.add(Flatten())

#red neuronal -> Fully connected
cnn.add(Dense(units = 128, activation = "relu"))

#capa de salida, para clasificacion binaria
cnn.add(Dense(units = 1, activation="sigmoid"))



#############
#Compilar la red
cnn.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

strDataTrain = "../input/cat-and-dog/training_set/training_set"
strDataTest = "../input/cat-and-dog/test_set/test_set"


from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale = 1./255.,
    shear_range=0.2,
    zoom_range = 0.2,
    horizontal_flip = True

)

#Preprocesamiento para test
test_datagen = ImageDataGenerator(
    rescale = 1./255.

)
#Configuracion de imagenes de entrada para train
train_set = train_datagen.flow_from_directory(
    strDataTrain,
    target_size = (64,64),
    batch_size = 32,
    class_mode ="binary"
)

#Configuracion de imagenes de entrada para test
test_set = test_datagen.flow_from_directory(
    strDataTest,
    target_size = (64,64),
    batch_size = 32,
    class_mode ="binary"
)


cnn.fit(train_set, epochs = 10, validation_data = test_set, verbose = 2)

cnn.save('PrimerModelo.h5')
