In [3]:
import numpy as np

In [4]:
# Escribamos nuevamente nuestros elementos y te invito a que pienses cual es la dimension de cada uno de ellos.

escalar = 5.6789
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
])

In [8]:
# La instruccion shape nos dice el valor de cada dimension para el objeto que estemos evaluando
print(escalar)
print(escalar.shape)
#Siempre y cuando nuestro objeto no sea un escalar, ya que no tiene dimension, es solo un numero.

5.6789


AttributeError: 'float' object has no attribute 'shape'

In [6]:
# Nuestro vector [3,4,5,6] tiene 1 sola dimension y eso es lo que nos responde dejando la segunda coordenada vacia
print(vector)
print(vector.shape)

[3 4 5 6]
(4,)


In [7]:
# Para vectores tambien podemos usar el comando len()
print(len(vector))
# Que nos devuelve la longitud del array

4


In [13]:
# Aqui vemos que la primer coordena de la respuesta corresponde a la cantidad de filas, y la segunda a la cantidad
# de columnas
print(matriz)
print(matriz.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [14]:
# Nos devuelve que nuestro tensor tiene dimension (3,3,3)
print(tensor)
print(tensor.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
(3, 3, 3)


In [16]:
# En esta oportunidad te invito a pensar al tensor como una evolución en el tiempo del evento que figura en la primer matriz. Esto es: en el tiempo 0 tenemos la cantidad de personas que se encuentran en cada habitación, la acción todavía no inició. Despues avanzamos a un tiempo 1, por ejemplo 10 minutos más tarde y llegan 10 personas a cada habitación. Esto lo vemos en la segunda matriz. 10 minutos más tarde en un tiempo 2, es la última de nuestras matrices que componen el tensor. 
print("Tiempo 0")
print(tensor[0])

print("Tiempo 1 o 10 minutos despues")
print(tensor[1])

print("Tiempo 2 o 20 minutos despues del inicio")
print(tensor[2])

Tiempo 0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Tiempo 1 o 10 minutos despues
[[11 12 13]
 [14 15 16]
 [17 18 19]]
Tiempo 2 o 20 minutos despues del inicio
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [18]:
#Ejercicios
# Calcula las dimensiones de los siguientes objetos
escalar = 9.8765
vector = np.array([1,2,3,4,5,6,7,8,9,0])
matriz = np.array([[1,2,3],[3,4,5],[5,6,7]])
tensor = np.array([
    [[1,2,3,4],[4,5,6,7],[7,8,9,10]],
    [[11,12,13,14],[14,15,16,17],[17,18,19,20]],
    [[21,22,23,24],[24,25,26,27],[27,28,29,30]],
])

In [20]:
# Validar las dimensiones de los objetos es de vital importancia, debemos estar seguros que al operar con nuestros
# objetos como resultado obtenemos un nuevo objeto de las dimensiones que estamos esperando
# Hay algunas operaciones que en Python por simplicidad o abuso del lenguaje podemos hacer aun cuando las
# dimensiones no coincidad y esto podria llevarnos a resultados inesperados que despues nos demandara mucho tiempo
# encontrar cual es la fuentel del error