### 1.

A partir del dataset mnist (tf.keras.datasets.cifar10.load_data()), realiza una clasificación usando:

** Las imágenes son a color, es decir, tienen 3 dimensiones (rgb). Para este problema, antes de empezar, transforma las imágenes a blanco y negro para que tengan 1 sola dimensión de profundidad **. 

1. Una CNN con:
    - 1 capa convolutiva con 8 neuronas
    - 1 MaxPool quedando las dimensiones de la imagen a la mitad
    - 1 dropout 0.25
    - 1 Flatten
    - 1 dense con 32 neuronas
    - 1 dense con 10 (salida)

2. Una CNN con:
    - 1 capa convolutiva con 8 neuronas
    - 1 MaxPool quedando las dimensiones de la imagen a la mitad
    - 1 dropout 0.25
    - 1 Flatten
    - 1 dense con 16 neuronas
    - 1 dense con 32 neuronas
    - 1 dense con 10 (salida)

¿ Cuál ha dado mejor resultado?

Para compilar el modelo, usa:

In [1]:
import tensorflow as tf
from tensorflow import keras
import cv2
# Librerias de ayuda
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.3.0


In [2]:
cifar10_data = keras.datasets.cifar10

(X_train, y_train), (X_test, y_test) = cifar10_data.load_data()

In [7]:
# con esto paso de 3 canales a uno
# aplico la funcion cv2.cvtColor a cada elemento de X_train y luego lo paso a array
new_array = [cv2.cvtColor(pic, cv2.COLOR_BGR2GRAY) for pic in X_train]
X_train = np.array(new_array)

In [8]:
new_array_t = [cv2.cvtColor(pic, cv2.COLOR_BGR2GRAY) for pic in X_test]
X_test = np.array(new_array_t)

In [9]:
# con esto normalizo los pixeles
X_train = X_train / 255.0
X_test = X_test / 255.0

In [10]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [11]:
# con esto saco los elementos (números) de dentro del array pequeño que solo tiene un número
# esto se llama flatten un array
y_train = np.array([num for arr in y_train for num in arr])
y_test = np.array([num for arr in y_test for num in arr])

In [12]:
y_train

array([6, 9, 9, ..., 9, 1, 1], dtype=uint8)

In [13]:
y_test

array([3, 8, 8, ..., 5, 1, 7], dtype=uint8)

In [14]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(50000, 32, 32) (10000, 32, 32) (50000,) (10000,)


In [15]:
X_train_gr = X_train.reshape(X_train.shape[0], 32, 32, 1)
X_test_gr = X_test.reshape(X_test.shape[0], 32, 32, 1)

print("train_images_gr shape:", X_train_gr.shape)
print("test_images_gr shape:", X_test_gr.shape)

train_images_gr shape: (50000, 32, 32, 1)
test_images_gr shape: (10000, 32, 32, 1)


1. Una CNN con:
    - 1 capa convolutiva con 8 neuronas
    - 1 MaxPool quedando las dimensiones de la imagen a la mitad
    - 1 dropout 0.25
    - 1 Flatten
    - 1 dense con 32 neuronas
    - 1 dense con 10 (salida)

In [17]:
INPUT_SHAPE = (32,32,1)

tf.config.run_functions_eagerly(True)

model = keras.models.Sequential()

model.add(keras.layers.Conv2D(filters=8, kernel_size=(5,5), strides=(1, 1),\
                              activation="relu", padding="valid", input_shape=INPUT_SHAPE))

model.add(keras.layers.MaxPool2D(pool_size=(2, 2)))


model.add(keras.layers.Dropout(rate=0.25)) 

model.add(keras.layers.Flatten())

model.add(keras.layers.Dense(units=32, activation="relu"))

model.add(keras.layers.Dense(units=10, activation="softmax"))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 8)         208       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 8)         0         
_________________________________________________________________
dropout (Dropout)            (None, 14, 14, 8)         0         
_________________________________________________________________
flatten (Flatten)            (None, 1568)              0         
_________________________________________________________________
dense (Dense)                (None, 32)                50208     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                330       
Total params: 50,746
Trainable params: 50,746
Non-trainable params: 0
____________________________________________________

In [18]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [19]:
X_train_gr.shape

(50000, 32, 32, 1)

In [20]:
y_train.shape

(50000,)

In [23]:
# el error es porque he parado el entrenamiento
model_history = model.fit(X_train_gr, y_train, validation_data=(X_test, y_test), verbose=1, epochs=10)

Epoch 1/10
1162/1563 [=====================>........] - ETA: 24s - loss: 1.4378 - accuracy: 0.5019

KeyboardInterrupt: 

### 2.

**BONUS: Entrena la red neuronal 1 pero esta vez con las imágenes a color.**