In [17]:
%matplotlib notebook

import numpy as np
np.set_printoptions(suppress=True) #para que NumPy muestre numeros cercanos a 0 como 0

In [18]:
# Si tienes la ecuacion 8 = 3+5*x y quieres saber el valor de x entonces necesitas despejar x
# para despejar x tiene que hacer la misma operacion de un lado y del otro del parentisis hasta que logras
# saber el valor de x
# (8)-3 = (3+5*x) - 3 = 5*x
# (8-3)/5 = (5*x)/5 = x
# de donde obtienes el valor de x = (8-3)/5 = 1
# Esto lo puedes validar reemplazando x en la ecucacion original para ver que la igual se cumple
print(8 == (3+5*1))

True


In [19]:
# Lo mismo ocurre con una sistema de ecuaciones lineales escrito en forma matricial, Como?
# Cuando tenemos el sistema A*x=b y sabemos los valores de la matriz A y el vector b, que valor de x hace que la 
# igualdad se cumpla? Para responder eso, o sea encontrar la solucion de A*x=b necesitamos poder pasar dividiendo A
# en realidad lo que queremos decir es que necesitamos poder deshacer la transformacion que la matriz A hizo en x
# para obtener b, pero eso es exactamente la inversa de A, ya que A*A_inv = Identidad pero tambien A_inv*A=Id

A = np.array([[3,1],[2,1]])
print(A) #Una matriz A

[[3 1]
 [2 1]]


In [20]:
b = np.array([[1],[1]]) # un vector columna que contiene las soluciones de cada ecuacion
#x = [x1, x2] # un vector compuesto por las 2 incognitas, aqui las llamamos x1, x2 pero podrian ser x e y
print(b)

[[1]
 [1]]


In [21]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1. -1.]
 [-2.  3.]]


In [22]:
# La solucion de este sistema de ecuaciones lineales es siguiendo el razonamiento anterior de despejar
# A*x = b => x = A_inv*b
x = A_inv.dot(b)
print(x)

[[0.]
 [1.]]


In [23]:
# Podemos comprobar que efectivamente esta es la solucion, hacer A*x nos tiene que dar b
print(A.dot(x))

[[1.]
 [1.]]


In [24]:
print(b)

[[1]
 [1]]


In [25]:
# Una vez que tengo A_inv puedo usarla para resolver la ecuacion para los valores de b que quiera?
# Si, efectivamente, no es necesario que volvamos a calcular la inversa para poder resolver el sistema
# Es por este motivo que en Algebra Lineal uno resuelve el sistema homogeneo, eso es cuando b es el vector 0
# Una vez tenemos esa solucion es simple resolver el sistema para cualquier valor de b, a eso se le llama buscar
# la solucion particular al sistema
b = [[3],[7]]
x = A_inv.dot(b)
print(x) # Es la solucion del sistema con el nuevo valor de b, y no fue necesario calcular A_inv

[[-4.]
 [15.]]


In [26]:
# Validando la solucion
print(A.dot(x))

[[3.]
 [7.]]


In [27]:
# Vale aclarar existen distintos algoritmos para encontrar la inversa de una matriz (cuando existe). Pero a efectos
# practicos la inversa solo se usa a nivel teorico, ya que tenemos limitaciones para representar computacionalmente
# los numeros en la matriz, esta limitacion esta dada por la precision de nuestra computadora digital.
# En la practica se utilizan algoritmos que usan el valor de b para obtener aproximaciones mas precisas de x, la
# solucion